apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-credentials
  namespace: ecommerce-namespace
type: Opaque //We are writing the values as base64 encoded strings (Not Plain Text). Opaque is the default type for secrets in Kubernetes. (Instead of opaque,docker registry or base auth or ssh auth etc)
data:
  RabbitMQ_UserName: Z3Vlc3Q=
  RabbitMQ_Password: Z3Vlc3Q=
